[build]
  command = "npm run build"  

[build.environment]
  # GDAL_STATIC="true"
  GDAL_HOME="/opt/buildhome/miniconda3/envs/gdal_env"
  RUST_BACKTRACE="1"

[functions]
  included_files = ["dylibs/**"]