[build]
  command = "npm run build"  

[build.environment]
  LD_LIBRARY_PATH="/opt/buildhome/miniconda3/envs/gdal_env/lib"
  GDAL_HOME="/opt/buildhome/miniconda3/envs/gdal_env"
  RUST_BACKTRACE="1"

[functions]
  included_files = ["dylibs/**"]