/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export enum Aspect {
  North = 'North',
  Northeast = 'Northeast',
  East = 'East',
  Southeast = 'Southeast',
  South = 'South',
  Southwest = 'Southwest',
  West = 'West',
  Northwest = 'Northwest',
  Flat = 'Flat'
}
export declare function pathfind(arrayBuffer: Buffer, start: string, end: string, excludedAspects?: Array<string> | undefined | null): Results
export declare class Results {
  pathLine: string
  pathPoints: string
}
