/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Aspect {
  North = 'North',
  Northeast = 'Northeast',
  East = 'East',
  Southeast = 'Southeast',
  South = 'South',
  Southwest = 'Southwest',
  West = 'West',
  Northwest = 'Northwest',
  Flat = 'Flat'
}
export declare function pathfind(geotiffBuffer: Buffer, start: string, end: string, excludedAspects?: Array<Aspect> | undefined | null): string
